site_name: Git 16 Jam
theme:
  name: material

nav:
  - Pendahuluan: 01-pendahuluan.md
  - Pengantar Praktis: 02-pengantar-praktis.md
  - Bab 1: 03-bab01.md
  - Bab 2: 04-bab02.md
  - Bab 3: 05-bab03.md
  - Bab 4: 06-bab04.md
  - Bab 5: 07-bab05.md
  - Bab 6: 08-bab06.md
  - Bab 7: 09-bab07.md
  - Bab 8: 10-bab08.md
  - Bab 9: 11-bab09.md
  - Bab 10: 12-bab10.md
  - Bab 11: 13-bab11.md
  - Bab 12: 14-bab12.md
  - Bab 13: 15-bab13.md
  - Bab 14: 16-bab14.md
  - Bab 15: 17-bab15.md
  - Bab 16: 18-bab16.md
  - Pengantar Refleksi: 19-pengantar-reflek.md
  - Bab 17: 20-babr17.md
  - Bab 18: 21-babr18.md
  - Bab 19: 22-babr19.md
  - Bab 20: 23-babr20.md
  - Bab 21: 24-babr21.md
  - Bab 22: 25-babr22.md
  - Bab 23: 26-babr23.md
  - Bab 24: 27-babr24.md
  - Ringkasan Akhir: 28-ringkas-akhir.md
  - Lampiran 1: 29-lampiran1.md
  - Lampiran 2: 30-lampiran2.md
  - Lampiran 3: 31-lampiran3.md
  - Lampiran 4: 32-lampiran4.md
  - Glosarium: 33-glosarium.md
  - Daftar Pustaka: 34-pustaka.md